
name: CI
on:
  pull_request:
    branches:
      - master
      - develop
      - feature/**
  push:
    branches:
      - '*'
      - '**'
jobs:
  build:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: test1
            os: [ self-hosted, linux, x64, ubuntu-latest ]
          - name: test2
            os: [ self-hosted, linux, x64, ubuntu-latest ]
          - name: test3
            os: [ self-hosted, linux, x64, ubuntu-latest ]
          - name: test4
            os: ubuntu-latest
          - name: test5
            os: ubuntu-latest
          - name: test6
            os: ubuntu-latest
    name: ${{ matrix.name }}
    timeout-minutes: 120
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test
        shell: bash
        run: |
          echo "Running the test"
          true
